When i make this geonear query :

     db.model('artisan').geoNear({
                type: "Point",
                coordinates: [43.4996, 3.60605]
            }, {
                distanceMultiplier: 0.001,
                maxDistance: 100000
            })


With the following indexe :

     {
      "v": 1,
      "key": {
        "loc": "2d"
      },
      "name": "loc_2d",
      "ns": "xxxx",
      "background": true
    }

I get the following error:

         MongoError: can't get query runner
    
    - error.js:31 Function.MongoError.create
       [app]/[mongoose]/[mongodb]/[mongodb-core]/lib/error.js:31:11
    
    - server.js:754
       [app]/[mongoose]/[mongodb]/[mongodb-core]/lib/topologies/server.js:754:66
    ...

I cant't find any documentation on the relation between the query runner and the geonear command, and no one seems to have this issue.

Precision: this is the only geo index in the schema, the only other index is in the _id field. The version id 2.

